[0m[[0m[0mdebug[0m] [0m[0m> Exec(run, Some(efd3a954-9acb-4150-a80d-d5534dba5dd9), Some(CommandSource(console0)))[0m
[0m[[0m[0mdebug[0m] [0m[0mEvaluating tasks: Compile / run[0m
[0m[[0m[0mdebug[0m] [0m[0mRunning task... Cancel: Signal, check cycles: false, forcegc: true[0m
[0m[[0m[31merror[0m] [0m[0mjava.lang.RuntimeException: Exception in Application start method[0m
[0m[[0m[31merror[0m] [0m[0m	at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:917)[0m
[0m[[0m[31merror[0m] [0m[0m	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$1(LauncherImpl.java:182)[0m
[0m[[0m[31merror[0m] [0m[0m	at java.lang.Thread.run(Unknown Source)[0m
[0m[[0m[31merror[0m] [0m[0mCaused by: akka.remote.RemoteTransportException: Failed to bind TCP to [192.168.1.116:20001] due to: Bind failed because of java.net.BindException: [/192.168.1.116:20001] Address already in use: bind[0m
[0m[[0m[31merror[0m] [0m[0m	at akka.remote.artery.tcp.ArteryTcpTransport$$anonfun$4.applyOrElse(ArteryTcpTransport.scala:273)[0m
[0m[[0m[31merror[0m] [0m[0m	at akka.remote.artery.tcp.ArteryTcpTransport$$anonfun$4.applyOrElse(ArteryTcpTransport.scala:267)[0m
[0m[[0m[31merror[0m] [0m[0m	at scala.concurrent.Future.$anonfun$recoverWith$1(Future.scala:417)[0m
[0m[[0m[31merror[0m] [0m[0m	at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:41)[0m
[0m[[0m[31merror[0m] [0m[0m	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)[0m
[0m[[0m[31merror[0m] [0m[0m	at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:63)[0m
[0m[[0m[31merror[0m] [0m[0m	at akka.dispatch.BatchingExecutor$Batch.run(BatchingExecutor.scala:81)[0m
[0m[[0m[31merror[0m] [0m[0m	at akka.dispatch.internal.SameThreadExecutionContext$$anon$1.unbatchedExecute(SameThreadExecutionContext.scala:21)[0m
[0m[[0m[31merror[0m] [0m[0m	at akka.dispatch.BatchingExecutor.execute(BatchingExecutor.scala:130)[0m
[0m[[0m[31merror[0m] [0m[0m	at akka.dispatch.BatchingExecutor.execute$(BatchingExecutor.scala:124)[0m
[0m[[0m[31merror[0m] [0m[0m	at akka.dispatch.internal.SameThreadExecutionContext$$anon$1.execute(SameThreadExecutionContext.scala:20)[0m
[0m[[0m[31merror[0m] [0m[0m	at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:72)[0m
[0m[[0m[31merror[0m] [0m[0m	at scala.concurrent.impl.Promise$DefaultPromise.$anonfun$tryComplete$1(Promise.scala:288)[0m
[0m[[0m[31merror[0m] [0m[0m	at scala.concurrent.impl.Promise$DefaultPromise.$anonfun$tryComplete$1$adapted(Promise.scala:288)[0m
[0m[[0m[31merror[0m] [0m[0m	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:288)[0m
[0m[[0m[31merror[0m] [0m[0m	at scala.concurrent.Promise.complete(Promise.scala:53)[0m
[0m[[0m[31merror[0m] [0m[0m	at scala.concurrent.Promise.complete$(Promise.scala:52)[0m
[0m[[0m[31merror[0m] [0m[0m	at scala.concurrent.impl.Promise$DefaultPromise.complete(Promise.scala:187)[0m
[0m[[0m[31merror[0m] [0m[0m	at scala.concurrent.Promise.failure(Promise.scala:104)[0m
[0m[[0m[31merror[0m] [0m[0m	at scala.concurrent.Promise.failure$(Promise.scala:104)[0m
[0m[[0m[31merror[0m] [0m[0m	at scala.concurrent.impl.Promise$DefaultPromise.failure(Promise.scala:187)[0m
[0m[[0m[31merror[0m] [0m[0m	at akka.stream.impl.io.ConnectionSourceStage$$anon$1.receive(TcpStages.scala:96)[0m
[0m[[0m[31merror[0m] [0m[0m	at akka.stream.impl.io.ConnectionSourceStage$$anon$1.$anonfun$preStart$1(TcpStages.scala:67)[0m
[0m[[0m[31merror[0m] [0m[0m	at akka.stream.impl.io.ConnectionSourceStage$$anon$1.$anonfun$preStart$1$adapted(TcpStages.scala:67)[0m
[0m[[0m[31merror[0m] [0m[0m	at akka.stream.stage.GraphStageLogic$StageActor.internalReceive(GraphStage.scala:241)[0m
[0m[[0m[31merror[0m] [0m[0m	at akka.stream.stage.GraphStageLogic$StageActor.$anonfun$callback$1(GraphStage.scala:202)[0m
[0m[[0m[31merror[0m] [0m[0m	at akka.stream.stage.GraphStageLogic$StageActor.$anonfun$callback$1$adapted(GraphStage.scala:202)[0m
[0m[[0m[31merror[0m] [0m[0m	at akka.stream.impl.fusing.GraphInterpreter.runAsyncInput(GraphInterpreter.scala:467)[0m
[0m[[0m[31merror[0m] [0m[0m	at akka.stream.impl.fusing.GraphInterpreterShell$AsyncInput.execute(ActorGraphInterpreter.scala:517)[0m
[0m[[0m[31merror[0m] [0m[0m	at akka.stream.impl.fusing.GraphInterpreterShell.processEvent(ActorGraphInterpreter.scala:625)[0m
[0m[[0m[31merror[0m] [0m[0m	at akka.stream.impl.fusing.ActorGraphInterpreter.akka$stream$impl$fusing$ActorGraphInterpreter$$processEvent(ActorGraphInterpreter.scala:800)[0m
[0m[[0m[31merror[0m] [0m[0m	at akka.stream.impl.fusing.ActorGraphInterpreter$$anonfun$receive$1.applyOrElse(ActorGraphInterpreter.scala:818)[0m
[0m[[0m[31merror[0m] [0m[0m	at akka.actor.Actor.aroundReceive(Actor.scala:537)[0m
[0m[[0m[31merror[0m] [0m[0m	at akka.actor.Actor.aroundReceive$(Actor.scala:535)[0m
[0m[[0m[31merror[0m] [0m[0m	at akka.stream.impl.fusing.ActorGraphInterpreter.aroundReceive(ActorGraphInterpreter.scala:716)[0m
[0m[[0m[31merror[0m] [0m[0m	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:580)[0m
[0m[[0m[31merror[0m] [0m[0m	at akka.actor.ActorCell.invoke(ActorCell.scala:548)[0m
[0m[[0m[31merror[0m] [0m[0m	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:270)[0m
[0m[[0m[31merror[0m] [0m[0m	at akka.dispatch.Mailbox.run(Mailbox.scala:231)[0m
[0m[[0m[31merror[0m] [0m[0m	at akka.dispatch.Mailbox.exec(Mailbox.scala:243)[0m
[0m[[0m[31merror[0m] [0m[0m	at java.util.concurrent.ForkJoinTask.doExec(Unknown Source)[0m
[0m[[0m[31merror[0m] [0m[0m	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(Unknown Source)[0m
[0m[[0m[31merror[0m] [0m[0m	at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)[0m
[0m[[0m[31merror[0m] [0m[0m	at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)[0m
[0m[[0m[31merror[0m] [0m[0mCaused by: akka.stream.impl.io.ConnectionSourceStage$$anon$1$$anon$2: Bind failed because of java.net.BindException: [/192.168.1.116:20001] Address already in use: bind[0m
[0m[[0m[31merror[0m] [0m[0mCaused by: java.net.BindException: [/192.168.1.116:20001] Address already in use: bind[0m
[0m[[0m[31merror[0m] [0m[0m	at sun.nio.ch.Net.bind0(Native Method)[0m
[0m[[0m[31merror[0m] [0m[0m	at sun.nio.ch.Net.bind(Unknown Source)[0m
[0m[[0m[31merror[0m] [0m[0m	at sun.nio.ch.Net.bind(Unknown Source)[0m
[0m[[0m[31merror[0m] [0m[0m	at sun.nio.ch.ServerSocketChannelImpl.bind(Unknown Source)[0m
[0m[[0m[31merror[0m] [0m[0m	at sun.nio.ch.ServerSocketAdaptor.bind(Unknown Source)[0m
[0m[[0m[31merror[0m] [0m[0m	at akka.io.TcpListener.liftedTree1$1(TcpListener.scala:60)[0m
[0m[[0m[31merror[0m] [0m[0m	at akka.io.TcpListener.<init>(TcpListener.scala:57)[0m
[0m[[0m[31merror[0m] [0m[0m	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)[0m
[0m[[0m[31merror[0m] [0m[0m	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)[0m
[0m[[0m[31merror[0m] [0m[0m	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)[0m
[0m[[0m[31merror[0m] [0m[0m	at java.lang.reflect.Constructor.newInstance(Unknown Source)[0m
[0m[[0m[31merror[0m] [0m[0m	at akka.util.Reflect$.instantiate(Reflect.scala:73)[0m
[0m[[0m[31merror[0m] [0m[0m	at akka.actor.ArgsReflectConstructor.produce(IndirectActorProducer.scala:101)[0m
[0m[[0m[31merror[0m] [0m[0m	at akka.actor.Props.newActor(Props.scala:226)[0m
[0m[[0m[31merror[0m] [0m[0m	at akka.actor.ActorCell.newActor(ActorCell.scala:616)[0m
[0m[[0m[31merror[0m] [0m[0m	at akka.actor.ActorCell.create(ActorCell.scala:643)[0m
[0m[[0m[31merror[0m] [0m[0m	at akka.actor.ActorCell.invokeAll$1(ActorCell.scala:514)[0m
[0m[[0m[31merror[0m] [0m[0m	at akka.actor.ActorCell.systemInvoke(ActorCell.scala:536)[0m
[0m[[0m[31merror[0m] [0m[0m	at akka.dispatch.Mailbox.processAllSystemMessages(Mailbox.scala:295)[0m
[0m[[0m[31merror[0m] [0m[0m	at akka.dispatch.Mailbox.run(Mailbox.scala:230)[0m
[0m[[0m[31merror[0m] [0m[0m	at akka.dispatch.Mailbox.exec(Mailbox.scala:243)[0m
[0m[[0m[31merror[0m] [0m[0m	at java.util.concurrent.ForkJoinTask.doExec(Unknown Source)[0m
[0m[[0m[31merror[0m] [0m[0m	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(Unknown Source)[0m
[0m[[0m[31merror[0m] [0m[0m	at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)[0m
[0m[[0m[31merror[0m] [0m[0m	at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)[0m
[0m[[0m[31merror[0m] [0m[0m(Compile / [31mrun[0m) Exception in Application start method[0m
[0m[[0m[31merror[0m] [0m[0mTotal time: 3 s, completed Nov 26, 2022 6:43:27 PM[0m
[0m[[0m[0mdebug[0m] [0m[0m> Exec(shell, None, None)[0m
[0m[[0m[31merror[0m] [0m[0mserver failed to start on local:sbt-server-2803f758b1deb20ef81b. java.io.IOException: Could not create lock for \\.\pipe\sbt-server-2803f758b1deb20ef81b_lock, error 5[0m
